#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_Bettina:
  path: /Bettina
  controller: App\Controller\BettinaController::getPersonalPage

cristea_ioan:
  path: /cristea_ioan
  controller: App\Controller\CristeaIoanController::index

bunulescu_stefan:
   path: /bunulescu_stefan
   controller: App\Controller\BunulescuStefan::index

blog_first_page:
  path: /blog
  controller: App\Controller\BlogController::getIndex

blog_post_page:
  path: /post?id={id}
  controller: App\Controller\BlogController::getPostPage

blog_new_post:
  path: /blog/new_post
  controller: App\Controller\BlogController::getNewPost

blog_edit_post:
  path: /blog/edit_post?id={id}
  controller: App\Controller\BlogController::getEditPost

blog_delete_post:
  path: /blog/delete_post?id={id}
  controller: App\Controller\BlogController::postDeletePost

app_Test1:
  path: /test1
  controller: App\Controller\BettinaController::getTest1Page

app_Test2:
  path: /test2
  controller: App\Controller\BettinaController::getTest2Page

app_Test3:
  path: /test3
  controller: App\Controller\BettinaController::getTest3Page

app_Test4:
  path: /test4
  controller: App\Controller\BettinaController::getTest4Page